# Generated by Django 4.2.4 on 2023-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
