# Generated by Django 4.2.4 on 2023-08-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
